startScene: scenes/test.yaml
window:
  title: Demo project
  viewport:
    width: 1280
    height: 720
  hints:
    visible: false
    resizable: true
    decorated: true
    focused: true
    maximized: false
rendering:
  options:
    defaultClearColor: !Color4f [0.1, 0.5, 1.0, 1.0]
    depthTest: true
    backFaceCulling: true
    lineWidth: 1.0
    fillPolygons: true
    blend: false
  viewport:
    scale: true
  shaders:
    version: version 450
    lights: 256